---
pipeline:
  trigger: 
    - main
  pool: self
  stages:
    - stage: image-build
      jobs:
        - job:
          steps:
            - script: docker image build -t gowthi1404/saleor-dashboard:dev-19122022 .
    - stage: push-image
      jobs:
        - job:
          steps:
            - script: docker image push gowthi1404/saleor-dashboard:dev-19122022
    
