---
trigger: 
  - main
pool: self
stages:
  - stage: image_build
    jobs:
      - job: dcoker_image_build
        steps:
          - script: docker image build -t gowthi1404/saleor-dashboard:dev-19122022 .
  - stage: push_image
    jobs:
      - job: docker_image_push
        steps:
          - script: docker image push gowthi1404/saleor-dashboard:dev-19122022
    
